debugging the invalid location for bq datasset issue

diff --git a/.github/workflows/ci_cd_pipeline.yaml b/.github/workflows/ci_cd_pipeline.yaml
--- a/.github/workflows/ci_cd_pipeline.yaml
+++ b/.github/workflows/ci_cd_pipeline.yaml
@@ -160,14 +160,15 @@ jobs:
       - name: Run dataform test
         working-directory: corpor_sales_dataform
         run: |
+          ls -la workflow_settings.yaml
           dataform compile
           dataform run --full-refresh --tags unit_test
       
-      - name: Clean up CI datasets
-        if: always()
-        run: |
-          RUN_ID=${{ github.run_id }}
-          bq rm -r -f -d "${{ env.GCP_PROJECT }}:df_ci_${RUN_ID}" ||  echo "Dataset may not exist. Skipping."
-          bq rm -r -f -d "${{ env.GCP_PROJECT }}:df_ci_${RUN_ID}_assertions" || echo "Assertion dataset may not exist. Skipping."
+      # - name: Clean up CI datasets
+      #   if: always()
+      #   run: |
+      #     RUN_ID=${{ github.run_id }}
+      #     bq rm -r -f -d "${{ env.GCP_PROJECT }}:df_ci_${RUN_ID}" ||  echo "Dataset may not exist. Skipping."
+      #     bq rm -r -f -d "${{ env.GCP_PROJECT }}:df_ci_${RUN_ID}_assertions" || echo "Assertion dataset may not exist. Skipping."
           
           
